// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzavRAB9Sx2dhSXzXxYkA0MWhGfJdF8rk',
    appId: '1:753679186938:web:1ccc6b9de006fa48ac4243',
    messagingSenderId: '753679186938',
    projectId: 'penjara-f796d',
    authDomain: 'penjara-f796d.firebaseapp.com',
    storageBucket: 'penjara-f796d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJSPHSrsSfOWGaXzOqvl-pGl-wZYu_AEo',
    appId: '1:753679186938:android:1684bea1c4f8bf87ac4243',
    messagingSenderId: '753679186938',
    projectId: 'penjara-f796d',
    storageBucket: 'penjara-f796d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYJ8dI0SIkQJBGb2bs_q_VBye8bEJ8prg',
    appId: '1:753679186938:ios:567113b691dbc0b5ac4243',
    messagingSenderId: '753679186938',
    projectId: 'penjara-f796d',
    storageBucket: 'penjara-f796d.firebasestorage.app',
    iosBundleId: 'com.example.penjara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYJ8dI0SIkQJBGb2bs_q_VBye8bEJ8prg',
    appId: '1:753679186938:ios:567113b691dbc0b5ac4243',
    messagingSenderId: '753679186938',
    projectId: 'penjara-f796d',
    storageBucket: 'penjara-f796d.firebasestorage.app',
    iosBundleId: 'com.example.penjara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzavRAB9Sx2dhSXzXxYkA0MWhGfJdF8rk',
    appId: '1:753679186938:web:716106a670cefde0ac4243',
    messagingSenderId: '753679186938',
    projectId: 'penjara-f796d',
    authDomain: 'penjara-f796d.firebaseapp.com',
    storageBucket: 'penjara-f796d.firebasestorage.app',
  );
}
